# Generated by Django 5.2.15 on 2026-06-23 10:41

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='location_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
